name: My First CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show files
        run: ls -la

      - name: Run health check
        run: |
          echo "Checking system..."
          echo "Build passed! ✅"
          echo "Date: $(date)"
          echo "All files:"
          ls

      - name: Done
        run: echo "Pipeline completed successfully! 🚀"
